services:

  db:
    container_name: go_db
    image: postgres:14.5-alpine
    restart: 'no'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=123456
      - POSTGRES_USER=go_db
    ports:
      - 5432:5432


volumes:
  pgdata:
